DELIMITER $$
CREATE PROCEDURE `sp_addToken`(
IN userID bigint,
IN emailID VARCHAR(255),
IN token VARCHAR(255)
)
BEGIN
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	INSERT into forgot_password values(userID,emailID,token);
	COMMIT;
END$$
DELIMITER ;
