DELIMITER $$

DROP PROCEDURE IF EXISTS sp_getAllCourseDetails $$

CREATE PROCEDURE `sp_getAllCourseDetails`()
BEGIN
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	SELECT *
	FROM course;

	COMMIT;
END $$;
DELIMITER ;