DELIMITER $$
CREATE DEFINER=`CSCI5308_22_DEVINT_USER`@`%` PROCEDURE `sp_updatePassword`(
IN emailID VARCHAR(255),
IN pswd VARCHAR(255)
)
BEGIN
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	UPDATE users set password = pswd where email = emailID;
	COMMIT;
END$$
DELIMITER ;
